name: "GitHub Notion Issues Automation"
permissions:
  issues: read
on: 
  issues:
      types: [opened, edited, deleted, transferred, milestoned, demilestoned, labeled, unlabeled, assigned, unassigned, locked, unlocked, reopened, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notion GitHub Issues Automation
        uses: Sajantoor/Notion-GitHub-Issues-Automation@latest
        with:
          repo: ${{ github.repository }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE: ${{ secrets.NOTION_DATABASE_ID }}
